### ISSUE TITLE
IDE Error Report (v4.2.3)

### ISSUE THREAD

**Issue by SaltOfTheFlame** [marhali/easy-i18n#187] opened 2022-10-14 10:47 UTC
# Additional information
/
# Exception trace
null
```
java.lang.NoClassDefFoundError: com/intellij/lang/javascript/psi/JSLiteralExpression
	at de.marhali.easyi18n.assistance.folding.JsFoldingBuilder.extractRegions(JsFoldingBuilder.java:22)
	at de.marhali.easyi18n.assistance.folding.AbstractFoldingBuilder.buildFoldRegions(AbstractFoldingBuilder.java:61)
	at de.marhali.easyi18n.assistance.folding.JsFoldingBuilder.buildFoldRegions(JsFoldingBuilder.java:19)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:89)
	at com.intellij.lang.folding.CompositeFoldingBuilder.buildFoldRegions(CompositeFoldingBuilder.java:36)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:89)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:72)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:272)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:238)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getUpdateResult(FoldingUpdate.java:88)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:72)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegions(CodeFoldingManagerImpl.java:226)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:212)
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: com.intellij.lang.javascript.psi.JSLiteralExpression PluginClassLoader(plugin=PluginDescriptor(name=Easy I18n, id=de.marhali.easyi18n, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\222.4345.14.plugins\easy-i18n, version=4.2.3, package=null, isBundled=false), packagePrefix=null, instanceId=148, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:214)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 34 more

```

**Comment by marhali** [comment] 2022-10-14 11:01
On which platform are you working on?

**Comment by SaltOfTheFlame** [comment] 2022-10-25 22:32
I am working on windows 10

**Comment by marhali** [comment] 2022-10-28 13:46
> Caused by: java.lang.ClassNotFoundException: com.intellij.lang.javascript.psi.JSLiteralExpression PluginClassLoader(plugin=PluginDescriptor(name=Easy I18n, id=de.marhali.easyi18n, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\222.4345.14.plugins\easy-i18n, version=4.2.3, package=null, isBundled=false), packagePrefix=null, instanceId=148, state=active)

So this line states that you are using IDEA-C which is missing the JavaScript/TypeScript plugin. Try to install this plugin or use a compatible JetBrains IDE.

**Comment by marhali** [comment] 2023-12-08 23:27
Duplicate of #344

**Closed by marhali** 2023-12-08 23:27 UTC
Labels: invalid
