### ISSUE TITLE
Enabling easyi18n plugin the folding feature on vue file doesnt work anymore

### ISSUE THREAD

**Issue by giolf** [marhali/easy-i18n#166] opened 2022-08-05 12:16 UTC
As i wrote in the title:
When the plugin is enabled, the folding feature in .vue files doesnt work anymore:
![image](https://user-images.githubusercontent.com/6743233/183075292-1482c6ae-0b9f-4f7c-a2dd-8bd72f5bd14e.png)
as you can see in the picture, on the left there is no way to collapse the tag elements in the template and in the script blocks.

**Comment by marhali** [comment] 2022-08-08 19:00
Duplicate of #126

**Closed** 2022-08-26 19:45 UTC
Labels: duplicate
