### ISSUE TITLE
When Easy I18n is enabled, block folding of *.js files does not work properly (v4.0.0)

### ISSUE THREAD

**Issue by FurryWolfX** [marhali/easy-i18n#126] opened 2022-05-11 11:58 UTC
WebStorm 2022.1

When Easy I18n is enabled, block folding of *.js files does not work properly (v4.0.0)

# enabled
![image](https://user-images.githubusercontent.com/12652119/167844047-e4961375-9a24-4e96-9bac-935dca200af5.png)

# disabled
![image](https://user-images.githubusercontent.com/12652119/167844133-c62e6115-04d5-4a73-91e3-b1b4feb77ba7.png)

**Comment by xithon** [comment] 2022-05-20 16:46
Can confirm that this also happens in Vue files (HTML and js) on PyCharm 2022.1.1

**Comment by marhali** [comment] 2022-05-20 16:54
AFAIK the current IntelliJ Folding API overrides existing folding regions if the plugin adds translation regions at some places. There is no support for ordering the folding regions or to keep them.

I am open to suggestions and hints on how to optimize these issues.

**Comment by samermurad** [comment] 2022-05-24 10:29
@marhali I haven't got the slightest clue about the IntelliJ APIs, but as a comparison,  This only happens to JavaScript files though, Typescript files are still functioning as expected, Although the plugin also knows how to open referenced translations keys
<img width="727" alt="Screenshot 2022-05-24 at 12 27 46" src="https://user-images.githubusercontent.com/7502854/170011056-2563007d-82c8-4a61-9079-49aab01d1c3d.png">

**Comment by markhalliwell** [comment] 2022-06-15 16:35
Have had to disable this plugin because of this issue; very annoying.

**Comment by xithon** [comment] 2022-07-06 09:15
Unfortunately this bug is still present in v4.1.1
I've just been disabling/enabling the plugin as a workaround

**Comment by flozdra** [comment] 2022-07-06 12:03
> AFAIK the current IntelliJ Folding API overrides existing folding regions if the plugin adds translation regions at some places

Can we create a setting to enable/disable the plugin to add translation regions? 
Personally, I don't think this is useful, at least not as useful as folding the code.

**Comment by flozdra** [comment] 2022-07-06 12:39
Thanks for the answer but it doesn't work using WebStorm 2022.1.3

**Comment by giolf** [comment] 2022-08-08 21:52
Unfortunately I had to disable the plug-in for this issue. @marhali i saw you opened a ticket. There are plans to fix it? As other users said: it happen only on specific extension files….

**Comment by marhali** [comment] 2022-08-09 09:08
> > > AFAIK the current IntelliJ Folding API overrides existing folding regions if the plugin adds translation regions at some places
> > 
> > 
> > Can we create a setting to enable/disable the plugin to add translation regions? Personally, I don't think this is useful, at least not as useful as folding the code.
> 
> You can disable `editor code assistance` via the plugin settings.

@giolf this might be an option for you.

**Comment by giolf** [comment] 2022-08-10 11:33
> > > > AFAIK the current IntelliJ Folding API overrides existing folding regions if the plugin adds translation regions at some places
> > > 
> > > 
> > > Can we create a setting to enable/disable the plugin to add translation regions? Personally, I don't think this is useful, at least not as useful as folding the code.
> > 
> > 
> > You can disable `editor code assistance` via the plugin settings.
> 
> @giolf this might be an option for you.

If i disabled it still code folding is not working plus i lost all the benefits of the plugin

**Comment by giolf** [comment] 2022-08-20 22:19
hey @marhali 

I see you updated the plugin with a new version.
It could be that with the new version the issue is solved?

**Comment by marhali** [comment] 2022-08-22 20:17
> hey @marhali
> 
> I see you updated the plugin with a new version. It could be that with the new version the issue is solved?

Not yet. Gonna test out some solutions this week.

Reminder 4 Me: test customFoldingProvider extension point / alternatively run and extend folding builder from the language's base implementation.

**Comment by giolf** [comment] 2022-08-22 20:48
> > hey @marhali
> > I see you updated the plugin with a new version. It could be that with the new version the issue is solved?
> 
> Not yet. Gonna test out some solutions this week.
> 
> Reminder 4 Me: test customFoldingProvider extension point / alternatively run and extend folding builder from the language's base implementation.

Cool thanks please update us in this topic.

many thanks

**Comment by marhali** [comment] 2022-08-24 19:25
Upcoming release version <kbd>4.2.2</kbd> should provide a fix for this.

**Comment by giolf** [comment] 2022-08-25 08:11
> Upcoming release version 4.2.2 should provide a fix for this.

It works. Many thanks

**Closed** 2022-08-26 19:44 UTC
Labels: bug
