### ISSUE TITLE
1.6 is not working

### ISSUE THREAD

**Issue by LifeIsStrange** [marhali/easy-i18n#65] opened 2021-12-02 18:07 UTC
Throw an expression about GSON type mismatch
I rolled back to 1.5.1 in the meantime (sorry don't have the time to reproduce and paste here the exception message)

**Comment by marhali** [comment] 2021-12-03 15:41
It would be great if an error message could be provided.

**Comment by marhali** [comment] 2021-12-07 10:06
Could not reproduce this issue. Please check if your translation file is properly formatted and no other files are in the specified directory.

**Comment by marhali** [comment] 2022-01-07 18:02
Closing this ticket now because it is based on an outdated version. If the error occurs on the newest version please open a new issue with the exception stack trace.

**Closed by marhali** 2022-01-07 18:02 UTC
Labels: question
